"/productos":
  get:
   summary: Obtener los productos
   tags:
    - Productos
   responses:
    "200":
     description: Los productos se obtuvieron correctamente
     content:
      application/json:
       schema:
        type: array
        items:
         $ref: "#components/schemas/productos"
    "500":
     description: Error interno del servidor
  post:
   summary: Crear producto
   tags:
    - Productos
   requestBody:
    required: true
    content:
     application/json:
      schema:
       $ref: "#components/schemas/ActualizarProductos"
   responses:
    "200":
     description: El producto se creo de forma correcta
     content:
      application/json:
       schema:
        type: object
        properties:
         status:
          type: string
         payload:
          $ref: "#components/schemas/Pet"
    "500":
     description: Error interno del servidor


     
   
